apiVersion: v1
kind: Namespace
metadata:
  name: koord-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: koordlet
  namespace: koord-system
  labels:
    name: koordlet
spec:
  selector:
    matchLabels:
      name: koordlet
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        name: koordlet
    spec:
      containers:
        - command:
            - /slo-agent
          args:
            - --logtostderr=true
            - --v=4
            - -CgroupRootDir=/host-cgroup/
            - -feature-gates=AllAlpha=true
          image: docker.io/koordinator-sh/koordlet:v0.1
          imagePullPolicy: Always
          name: koordlet
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 0
              memory: 0
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          volumeMounts:
          - mountPath: /etc/localtime
            name: host-time
            readOnly: true
          - mountPath: /host-cgroup/
            name: host-cgroup-root
          - mountPath: /host-sys-fs/
            name: host-sys-fs
            mountPropagation: Bidirectional
          - mountPath: /host-var-run/
            name: host-var-run
            readOnly: true
          - mountPath: /host-sys/
            name: host-sys
            readOnly: true
      tolerations:
        - operator: Exists
      hostNetwork: true
      hostPID: true
      terminationGracePeriodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      serviceAccount: koordlet
      serviceAccountName: koordlet
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
        - hostPath:
            path: /sys/fs/cgroup/
            type: ""
          name: host-cgroup-root
        - hostPath:
            path: /sys/fs/
            type: ""
          name: host-sys-fs
        - hostPath:
            path: /var/run/
            type: ""
          name: host-var-run
        - hostPath:
            path: /sys/
            type: ""
          name: host-sys
