---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: scheduleexplanations.scheduling.koordinator.sh
spec:
  group: scheduling.koordinator.sh
  names:
    kind: ScheduleExplanation
    listKind: ScheduleExplanationList
    plural: scheduleexplanations
    shortNames:
    - sched-exp
    singular: scheduleexplanation
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              questionObjectKey:
                description: |-
                  QuestionObjectKey is the key of the QuestionObject.
                  For pod, it is namespace/name; for job, it is namespace/jobName; for pod with gangGroupAnnotation, it is gangGroupIDs.
                type: string
              questionObjectTemplate:
                description: QuestionObjectTemplate defines the questioned pod template.
                  Now it is unsupported
                x-kubernetes-preserve-unknown-fields: true
              ttl:
                default: 24h
                description: |-
                  Time-to-Live period for the explanation CR.
                  Defaults to 24h. Set 0 to disable expiration.
                type: string
            type: object
          status:
            properties:
              detailedExplanation:
                description: DetailedExplanation indicates the detailed explanation
                  in each topology domain.
                items:
                  properties:
                    failedMessage:
                      description: FailedMessage indicates the reason for the QuestionObject
                        can't be scheduled in this topology domain.
                      type: string
                    nodePossibleVictims:
                      description: NodePossibleVictims indicates the possible victims
                        for members that can't be scheduled.
                      items:
                        properties:
                          nodeName:
                            type: string
                          possibleVictims:
                            items:
                              properties:
                                isNominatedPod:
                                  type: boolean
                                name:
                                  type: string
                                namespace:
                                  type: string
                                uid:
                                  type: string
                              type: object
                            type: array
                        type: object
                      type: array
                    preemptExplanation:
                      properties:
                        failedMessage:
                          description: FailedMessage indicates the reason for the
                            QuestionObject can't be scheduled in this topology domain.
                          type: string
                        feasibleSchedulingResult:
                          description: |-
                            FeasibleSchedulingResult indicates the possible scheduling results.
                            If the QuestionObject can be scheduled, it returns the scheduling result for members that can be partially scheduled.
                          items:
                            properties:
                              name:
                                type: string
                              namespace:
                                type: string
                              nodeName:
                                type: string
                              uid:
                                type: string
                            type: object
                          type: array
                        nodeFailedDetails:
                          description: NodeFailedDetails If the QuestionObject cannot
                            be scheduled, provide the reason for each node.
                          items:
                            properties:
                              failedNodes:
                                items:
                                  type: string
                                type: array
                              failedPlugin:
                                type: string
                              preemptMightHelp:
                                type: boolean
                              reason:
                                type: string
                            type: object
                          type: array
                        schedulable:
                          description: Schedulable indicates whether the QuestionObject
                            can be scheduled.
                          type: boolean
                      type: object
                    schedulable:
                      description: Schedulable indicates whether the QuestionObject
                        can be scheduled.
                      type: boolean
                    scheduleExplanation:
                      properties:
                        failedMessage:
                          description: FailedMessage indicates the reason for the
                            QuestionObject can't be scheduled in this topology domain.
                          type: string
                        feasibleSchedulingResult:
                          description: |-
                            FeasibleSchedulingResult indicates the possible scheduling results.
                            If the QuestionObject can be scheduled, it returns the scheduling result for members that can be partially scheduled.
                          items:
                            properties:
                              name:
                                type: string
                              namespace:
                                type: string
                              nodeName:
                                type: string
                              uid:
                                type: string
                            type: object
                          type: array
                        nodeFailedDetails:
                          description: NodeFailedDetails If the QuestionObject cannot
                            be scheduled, provide the reason for each node.
                          items:
                            properties:
                              failedNodes:
                                items:
                                  type: string
                                type: array
                              failedPlugin:
                                type: string
                              preemptMightHelp:
                                type: boolean
                              reason:
                                type: string
                            type: object
                          type: array
                        schedulable:
                          description: Schedulable indicates whether the QuestionObject
                            can be scheduled.
                          type: boolean
                      type: object
                    topologyDomain:
                      description: TopologyDomain indicates the topology domain.
                      type: string
                  type: object
                type: array
              failedMessage:
                description: FailedMessage indicates the reason for the QuestionObject
                  can't be scheduled.
                type: string
              schedulable:
                description: Schedulable indicates whether the QuestionObject can
                  be scheduled.
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
